# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: debian:buster

stages:
  - deploy
  - debug

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

Deploy vkrsmrt-dev-www:
  stage: deploy
  variables:
    TARGET_PATH: "/srv/app021_dev_vkr_smart_ru"
    TARGET_HOST: "192.168.19.157"
    TARGET_PHP_PATH: "/usr/bin/php8.1"
  script:
    - echo "Do your build here"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$TARGET_PRIVKEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $TARGET_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -ar $PWD/* $TARGET_HOST:$TARGET_PATH
    - ssh $TARGET_HOST "cd $TARGET_PATH/ && composer update"
    - ssh $TARGET_HOST "cd $TARGET_PATH/ && composer install"
    - ssh $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan migrate"
    - ssh $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan view:clear"
    - ssh $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan cache:clear"
    - ssh $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan route:clear"
    - ssh $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan config:cache"
  only:
    refs:
      - develop


Deploy vkrsmrt-www:
  stage: deploy
  variables:
    TARGET_PATH: "/srv/vkrsmrt-www"
    TARGET_HOST: "5.188.137.225"
    TARGET_SSH_PORT: "133"
    TARGET_PHP_PATH: "/usr/bin/php8.2"
  script:
    - echo "Do your build here"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client rsync -y )'
    - eval $(ssh-agent -s)
    - echo "$TARGET_PRIVKEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p$TARGET_SSH_PORT $TARGET_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync -ar -e "ssh -p $TARGET_SSH_PORT" $PWD/* $TARGET_HOST:$TARGET_PATH
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "cd $TARGET_PATH/ && composer update"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "cd $TARGET_PATH/ && composer install"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan migrate"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan view:clear"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan cache:clear"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan route:clear"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan config:cache"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "$TARGET_PHP_PATH $TARGET_PATH/artisan config:cache"
    - ssh -p$TARGET_SSH_PORT $TARGET_HOST "/usr/bin/IPRdjango \"На vkr-smart.ru задеплоен комит https://git.iprmedia.ru/gitlab/vkrsmrt/vkrsmrt-www/-/commit/$CI_COMMIT_SHA\" developers"
  only:
    refs:
      - master

get dev log:
  stage: debug
  variables:
    SRC_PATH: "/srv/app021_dev_vkr_smart_ru"
    SRC_HOST: "192.168.19.157"
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$TARGET_PRIVKEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SRC_HOST >> ~/.ssh/known_hosts
    - scp $SRC_HOST:/$SRC_PATH/storage/logs/laravel.log .
  artifacts:
    paths:
      - laravel.log
    expire_in: 1 week
  when: manual
